[CI] Fix the Windows CI builds
Looks like the pynsist config needs to be in the root directory to work properly
```
Unpacking Python...
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\a\unmanic-desktop-launcher\unmanic-desktop-launcher\venv\lib\site-packages\nsist\__main__.py", line 2, in <module>
    main()
  File "D:\a\unmanic-desktop-launcher\unmanic-desktop-launcher\venv\lib\site-packages\nsist\__init__.py", line 533, in main
    ec = InstallerBuilder(**args).run(makensis=(not options.no_makensis))
  File "D:\a\unmanic-desktop-launcher\unmanic-desktop-launcher\venv\lib\site-packages\nsist\__init__.py", line 479, in run
    self.prepare_shortcuts()
  File "D:\a\unmanic-desktop-launcher\unmanic-desktop-launcher\venv\lib\site-packages\nsist\__init__.py", line 322, in prepare_shortcuts
    shutil.copy2(sc['icon'], self.build_dir)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'launcher\\assets\\icon.ico'
```